### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BhujayKumarBhatta**
hdbscan installation through pip fails to work with pytorch  within Anaconda environment

### CODE REVIEW

**Comment by BhujayKumarBhatta** [comment]
please hold this , hdbscan installation is solved but the pipeline.py is giving error in the attention module. I will update.

**Comment by YangLin-George** [comment]
@BhujayKumarBhatta Thanks for your attention. 

Current knowing issues including hdbscan (which is caused by joblib), and overrides (it should be something related to the signature checking).

If the issue in Attention is telling you that the return type is unexpected, please **try update overrides**, and add `check_signature=False` in the braces of `@override` annotation.

As for the error in hdbscan caused by joblib. You can try **downgrade scikit-learn to 0.24.**  It works for me.

If anything wrong, please let me know.

**Comment by BhujayKumarBhatta** [comment]
thanks for your reply.  The installation that worked are as follows:  
conda install pytorch==1.5.1 torchvision==0.6.1 -c pytorch
conda install -c conda-forge hdbscan==0.8.26
conda install -c conda-forge overrides==3.1.0
The error that is coming is:
(pelog383) bhujay@DESKTOP-MQIKKH7:/mnt/c/Users/Bhujay_ROG/MyDev/PLELog$ python pipeline.py --config_file config/HDFS.cfg --dataset HDFS
Traceback (most recent call last):
  File "pipeline.py", line 372, in <module>
    result = main_process(save_path=save_path, pre_train=pre_train, pre_dev=pre_dev, pre_test=pre_test, ratios=ratios,
  File "pipeline.py", line 235, in main_process
    mpl.use('Agg')
NameError: name 'mpl' is not defined

**Comment by YangLin-George** [comment]
Thanks for the info.

mlp is short for matplotlib, this may be some redundant code while we were doing visual analytics.

We're working on a new version of PLELog, the issues you found will be carefully taken care of. 

Thanks again for your attention!

**Pull request closed without merging**
